version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatapp-backend
    command: >
      daphne -b 0.0.0.0 -p 8000 config.asgi:application
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
    networks:
      - kaiwa_network

  redis:
    image: redis:7-alpine
    container_name: chatapp-redis
    ports:
      - "6379:6379"
    networks:
      - kaiwa_network

networks:
  kaiwa_network:
    external: true
